services:
  ragnar:
    platform: linux/amd64
    build: .
    container_name: ragnar
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - ./audio:/app/audio
      - ./text:/app/text
      - ./cache:/app/cache